name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build the project
        run: mvn clean package -Dquarkus.package.type=uber-jar

      - name: Build Docker image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t chaimabouhlel/quarkus-containerized-app:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

      - name: Push Docker image
        run: |
          docker push chaimabouhlel/quarkus-containerized-app:latest
